Genre.create!([
  {category: "action", image_file_name: "action.jpg"},
  {category: "thriller", image_file_name: "thriller.jpg"},
  {category: "horror", image_file_name: "horror.jpg"},
  {category: "drama", image_file_name: "drama.jpg"},
  {category: "comedy", image_file_name: "comedy.jpg"},
  {category: "science fiction", image_file_name: "science_fiction.jpg"},
  {category: "fantasy", image_file_name: "fantasy.jpg"},
  {category: "romance", image_file_name: "romance.jpg"}
])
Movie.create!([
  {genre_id: 2, title: "Iron Man", rating: "PG-13", total_gross: "318412101.0", description: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.", released_on: "2008-05-02", cast: "Robert Downey Jr., Terrence Howard, Jeff Bridges, Gwyneth Paltrow, Leslie Bibb", director: "Jon Favreau", duration: "2h 6m", image_file_name: "iron_man.jpg", trailer: "https://www.youtube.com/embed/8hYlB38asDY"},
  {genre_id: 1, title: "Batman", rating: "PG-13", total_gross: "533345358.0", description: "Having witnessed his parents' brutal murder as a child, millionaire philanthropist Bruce Wayne fights crime in Gotham City disguised as Batman, a costumed hero who strikes fear into the hearts of villains. But when a deformed madman who calls himself \"The Joker\" seizes control of Gotham's criminal underworld, Batman must face his most ruthless nemesis ever while protecting both his identity and his love interest, reporter Vicki Vale.", released_on: "1989-06-23", cast: "Michael Keaton, Jack Nicholson, Kim Basinger, Robert Wuhl, Michael Gough", director: "Tim Burton", duration: "2h 6m", image_file_name: "batman.jpg", trailer: "https://www.youtube.com/embed/dgC9Q0uhX70"},
  {genre_id: 6, title: "Avengers: Endgame", rating: "PG-13", total_gross: "0.0", description: "Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.", released_on: "2019-04-26", cast: "Chris Evans, Robert Downey Jr., Scarlett Johansson, Mark Ruffalo", director: "Anthony Russo, Joe Russo", duration: "3h 2m", image_file_name: "endgame.jpg", trailer: "https://www.youtube.com/embed/TcMBFSGVi1c"},
  {genre_id: 7, title: "Spider-Man: Far From Home", rating: "PG-13", total_gross: "0.0", description: "Peter Parker's relaxing European vacation takes an unexpected turn when Nick Fury suddenly shows up in his hotel room. Parker soon finds himself donning the Spider-Man suit to help Fury stop the evil Mysterio from wreaking havoc across the continent.", released_on: "2019-07-05", cast: "Tom Holland, Jake Gyllenhaal, Zendaya, Marisa Tomei", director: "Jon Watts", duration: "N/A", image_file_name: "spiderman_far_from_home.jpg", trailer: "https://www.youtube.com/embed/DYYtuKyMtY8"},
  {genre_id: 4, title: "Brightburn", rating: "NR", total_gross: "0.0", description: "What if a child from another world crash-landed on Earth, but instead of becoming a hero to mankind, he proved to be something far more sinister?", released_on: "2019-05-24", cast: "Jackson A. Dunn, David Yarovesky, Elizabeth Banks, David Denman", director: "David Yarovesky", duration: "N/A", image_file_name: "brightburn.jpg", trailer: "https://www.youtube.com/embed/oD1vbhicJUY"},
  {genre_id: 6, title: "Inception", rating: "PG-13", total_gross: "292576195.0", description: "Dom Cobb is a thief with the rare ability to enter people's dreams and steal their secrets from their subconscious. His skill has made him a hot commodity in the world of corporate espionage but has also cost him everything he loves. Cobb gets a chance at redemption when he is offered a seemingly impossible task: Plant an idea in someone's mind. If he succeeds, it will be the perfect crime, but a dangerous enemy anticipates Cobb's every move.", released_on: "2010-07-13", cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy, Ken Watanabe", director: "Christopher Nolan", duration: "2h 28m", image_file_name: "inception.jpg", trailer: "https://www.youtube.com/embed/8hP9D6kZseM"},
  {genre_id: 8, title: "Aladdin", rating: "NR", total_gross: "0.0", description: "A kindhearted Arabian street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make the deepest wishes come true.", released_on: "2019-05-24", cast: "Will Smith, Mena Massoud, Nasim Pedrad, Naomi Scott", director: "Guy Ritchie", duration: "N/A", image_file_name: "aladdin.jpg", trailer: "https://www.youtube.com/embed/foyufD52aog"},
  {genre_id: 6, title: "Star Wars: Episode IV - A New Hope", rating: "PG", total_gross: "307263857.0", description: "The Imperial Forces -- under orders from cruel Darth Vader hold Princess Leia hostage, in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker and Han Solo, captain of the Millennium Falcon, work together with the companionable droid duo R2-D2 and C-3PO to rescue the beautiful princess, help the Rebel Alliance, and restore freedom and justice to the Galaxy.", released_on: "1977-05-25", cast: " Carrie Fisher, Mark Hamill, Harrison Ford, Anthony Daniels", director: "George Lucas", duration: "2h 5m", image_file_name: "starwarsnewhope.jpg", trailer: "https://www.youtube.com/embed/vZ734NWnAHA"},
  {genre_id: 4, title: "Superman", rating: "PG", total_gross: "134218018.0", description: "An alien orphan is sent from his dying planet to Earth, where he grows up to become his adoptive home's first and greatest superhero.", released_on: "1978-12-15", cast: "Christopher Reeve, Gene Hackman, Marlon Brando, Margot Kidder, Terence Stamp", director: "Richard Donner", duration: "3h 8m", image_file_name: "superman.jpg", trailer: "https://www.youtube.com/embed/zHaKVHOjtiw"},
  {genre_id: 1, title: "Spider-Man", rating: "PG", total_gross: "403706375.0", description: "When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he eventually must use to fight evil as a superhero after tragedy befalls his family.", released_on: "2002-05-03", cast: "Tobey Maguire, Willem Dafoe, Kirsten Dunst, James Franco, Cliff Robertson, Rosemary Harris, J.K. Simmons", director: "Sam Raimi", duration: "2h 1m", image_file_name: "spiderman.jpg", trailer: "https://www.youtube.com/embed/BWsLc3j1AWg"},
  {genre_id: 5, title: "Napoleon Dynamite", rating: "PG", total_gross: "44940956.0", description: "A listless and alienated teenager decides to help his new friend win the class presidency in their small western high school, while he must deal with his bizarre family life back home.", released_on: "2004-06-11", cast: "Jon Heder, Efren Ramirez, Tina Majorino, Jon Gries", director: "Jared Hess", duration: "1h 36m", image_file_name: "napoleon_dynamite.jpg", trailer: "https://www.youtube.com/embed/qH-FBPRf7NQ?start=6"},
  {genre_id: 3, title: "It", rating: "R", total_gross: "327481748.0", description: "Seven young outcasts in Derry, Maine, are about to face their worst nightmare -- an ancient, shape-shifting evil that emerges from the sewer every 27 years to prey on the town's children. Banding together over the course of one horrifying summer, the friends must overcome their own personal fears to battle the murderous, bloodthirsty clown known as Pennywise.", released_on: "2017-09-08", cast: "Bill Skarsgård, Jaeden Lieberher, Jeremy Ray Taylor, Sophia Lillis, Finn Wolfhard, Jack Dylan Grazer", director: "Andrés Muschietti", duration: "2h 15m", image_file_name: "it.jpg", trailer: "https://www.youtube.com/embed/xKJmEC5ieOk"}
])
